# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-17 12:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_operations', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Followers',
            new_name='Follower',
        ),
        migrations.RenameModel(
            old_name='Tweets',
            new_name='Tweet',
        ),
    ]
