# -*- coding: utf-8 -*-
# Generated by Django 1.9.8 on 2019-03-18 10:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('twitter_operations', '0003_auto_20190318_0431'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='follower',
            unique_together=set([('follower_user', 'followed_user')]),
        ),
        migrations.AlterUniqueTogether(
            name='liketweet',
            unique_together=set([('user', 'tweet')]),
        ),
    ]
